//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.10 at 08:40:26 AM ICT 
//

package com.bkav.edoc.service.entity.soapenv;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.bkav.edoc.service.entity.edxml.MessageHeader;
import com.bkav.edoc.service.entity.edxml.TraceHeaderList;


/**
 * <p>
 * Java class for Header complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Header">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageHeader" type="{http://schemas.xmlsoap.org/soap/envelope/}MessageHeader"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Header", propOrder = {"messageHeader"})
public class Header {

    @XmlElement(name = "MessageHeader", required = true)
    protected MessageHeader messageHeader;
    private TraceHeaderList traceHeaderList;

    /**
     * Gets the value of the messageHeader property.
     *
     * @return possible object is {@link MessageHeader }
     */
    public MessageHeader getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     *
     * @param value allowed object is {@link MessageHeader }
     */
    public void setMessageHeader(MessageHeader value) {
        this.messageHeader = value;
    }

    /**
     * @return the traceHeaderList
     */
    public TraceHeaderList getTraceHeaderList() {
        return traceHeaderList;
    }

    /**
     * @param traceHeaderList the traceHeaderList to set
     */
    public void setTraceHeaderList(TraceHeaderList traceHeaderList) {
        this.traceHeaderList = traceHeaderList;
    }

}
