//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.10 at 08:40:26 AM ICT 
//


package com.bkav.edoc.service.entity.edxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Author complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Author">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Competence" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Function" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Author", propOrder = {
        "competence",
        "function",
        "fullName"
})
public class Author {

    @XmlElement(name = "Competence", required = true)
    protected String competence;
    @XmlElement(name = "Function", required = true)
    protected String function;
    @XmlElement(name = "FullName", required = true)
    protected String fullName;

    /**
     * Gets the value of the competence property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCompetence() {
        return competence;
    }

    /**
     * Sets the value of the competence property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCompetence(String value) {
        this.competence = value;
    }

    /**
     * Gets the value of the function property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFunction(String value) {
        this.function = value;
    }

    /**
     * Gets the value of the fullName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

}
