//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.10 at 08:40:26 AM ICT 
//


package com.bkav.edoc.service.entity.edxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OtherInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtherInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Priority" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="SphereOfPromulgation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TyperNotation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PromulgationAmount" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="PageAmount" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtherInfo", propOrder = {
    "priority",
    "sphereOfPromulgation",
    "typerNotation",
    "promulgationAmount",
    "pageAmount"
})
public class OtherInfo {

    @XmlElement(name = "Priority")
    @XmlSchemaType(name = "unsignedShort")
    protected int priority;
    @XmlElement(name = "SphereOfPromulgation", required = true)
    protected String sphereOfPromulgation;
    @XmlElement(name = "TyperNotation", required = true)
    protected String typerNotation;
    @XmlElement(name = "PromulgationAmount")
    @XmlSchemaType(name = "unsignedShort")
    protected int promulgationAmount;
    @XmlElement(name = "PageAmount")
    @XmlSchemaType(name = "unsignedShort")
    protected int pageAmount;

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

    /**
     * Gets the value of the sphereOfPromulgation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSphereOfPromulgation() {
        return sphereOfPromulgation;
    }

    /**
     * Sets the value of the sphereOfPromulgation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSphereOfPromulgation(String value) {
        this.sphereOfPromulgation = value;
    }

    /**
     * Gets the value of the typerNotation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTyperNotation() {
        return typerNotation;
    }

    /**
     * Sets the value of the typerNotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTyperNotation(String value) {
        this.typerNotation = value;
    }

    /**
     * Gets the value of the promulgationAmount property.
     * 
     */
    public int getPromulgationAmount() {
        return promulgationAmount;
    }

    /**
     * Sets the value of the promulgationAmount property.
     * 
     */
    public void setPromulgationAmount(int value) {
        this.promulgationAmount = value;
    }

    /**
     * Gets the value of the pageAmount property.
     * 
     */
    public int getPageAmount() {
        return pageAmount;
    }

    /**
     * Sets the value of the pageAmount property.
     * 
     */
    public void setPageAmount(int value) {
        this.pageAmount = value;
    }

}
