//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.24 at 08:47:59 AM ICT 
//

package com.bkav.edoc.service.entity.edxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for StaffInfo complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="StaffInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Department" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Staff" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StaffInfo", propOrder = { "department", "staff" })
public class StaffInfo {

	@XmlElement(name = "Department", required = true)
	protected String department;
	@XmlElement(name = "Staff", required = true)
	protected String staff;
	@XmlElement(name = "Email", required = true)
	protected String email;
	@XmlElement(name = "Mobile", required = true)
	protected String mobile;

	/**
	 * Gets the value of the department property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * Sets the value of the department property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDepartment(String value) {
		this.department = value;
	}

	/**
	 * Gets the value of the staff property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStaff() {
		return staff;
	}

	/**
	 * Sets the value of the staff property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStaff(String value) {
		this.staff = value;
	}

	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return the mobile
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * @param mobile the mobile to set
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}
