//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.24 at 09:38:49 AM ICT 
//

package com.bkav.edoc.service.entity.edxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Status complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Status">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResponseFor" type="{http://schemas.xmlsoap.org/soap/envelope/}ResponseFor"/>
 *         &lt;element name="From" type="{http://schemas.xmlsoap.org/soap/envelope/}From"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StaffInfo" type="{http://schemas.xmlsoap.org/soap/envelope/}StaffInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Status", propOrder = { "responseFor", "from", "description",
		"timeStamp", "statusCode", "staffInfo" })
public class Status {

	@XmlElement(name = "ResponseFor", required = true)
	protected ResponseFor responseFor;
	@XmlElement(name = "From", required = true)
	protected From from;
	@XmlElement(name = "Description", required = true)
	protected String description;
	@XmlElement(name = "TimeStamp", required = true)
	protected String timeStamp;
	@XmlElement(name = "StatusCode", required = true)
	protected String statusCode;
	@XmlElement(name = "StaffInfo", required = true)
	protected StaffInfo staffInfo;

	/**
	 * Gets the value of the responseFor property.
	 * 
	 * @return possible object is {@link ResponseFor }
	 * 
	 */
	public ResponseFor getResponseFor() {
		return responseFor;
	}

	/**
	 * Sets the value of the responseFor property.
	 * 
	 * @param value
	 *            allowed object is {@link ResponseFor }
	 * 
	 */
	public void setResponseFor(ResponseFor value) {
		this.responseFor = value;
	}

	/**
	 * Gets the value of the from property.
	 * 
	 * @return possible object is {@link From }
	 * 
	 */
	public From getFrom() {
		return from;
	}

	/**
	 * Sets the value of the from property.
	 * 
	 * @param value
	 *            allowed object is {@link From }
	 * 
	 */
	public void setFrom(From value) {
		this.from = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the timeStamp property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTimeStamp() {
		return timeStamp;
	}

	/**
	 * Sets the value of the timeStamp property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTimeStamp(String value) {
		this.timeStamp = value;
	}

	/**
	 * Gets the value of the statusCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatusCode() {
		return statusCode;
	}

	/**
	 * Sets the value of the statusCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStatusCode(String value) {
		this.statusCode = value;
	}

	/**
	 * Gets the value of the staffInfo property.
	 * 
	 * @return possible object is {@link StaffInfo }
	 * 
	 */
	public StaffInfo getStaffInfo() {
		return staffInfo;
	}

	/**
	 * Sets the value of the staffInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link StaffInfo }
	 * 
	 */
	public void setStaffInfo(StaffInfo value) {
		this.staffInfo = value;
	}

}
